apiVersion: v1
kind: ConfigMap
metadata:
  name: wtn-email-configmap
data:
  DATASOURCE_USERNAME: "appwtn"
  DATASOURCE_PASSWORD: "appwtn"
  DATASOURCE_URL: "jdbc:postgresql://postgres/wtndbdev"
  EMAIL_ADMIN: jpenalver@wtrasnet.com
  EMAIL_DEFAULT_SENDER: default-sender@wtrasnet.com
  FILE_RESOURCE_LOADER_PATH: /email/
  SMTP_HOST: mail.wtransnet.local
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  TEMPLATES_CONFIG_DIR: /email/email-config/
  TEMPLATES_DIR: /email/