apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data:
  user: "username"
  password: "password"
  virtualhost: "/"
  RABBITMQ_VHOST: "/"
  RABBITMQ_DEFAULT_USER: "username"
# Esta variable la coje rabbit
  RABBITMQ_DEFAULT_PASS: "password"
# Esta variable la cojen los wtn-*
  RABBIT_PASSWORD: "password"