apiVersion: v1
kind: ConfigMap
metadata:
  name: wtn-remote-log-configmap
data:
  MICROSERVICE_NAME: wtn-remote-log
  # En caso de arrancar con gradle, indicarle donde dejar lo que se descarga de Nexus:  
  GRADLE_USER_HOME: "/docker/gradle_user_home/wtn-remote-log"